### ISSUE TITLE
Use alpine:3.5 base image?

### ISSUE THREAD

**Issue by misolietavec** [jupyter/tmpnb#270] opened 2017-04-17 11:01 UTC
I forked this repository as [misolietavec/tmpnb](https://github.com/misolietavec/tmpnb) where the Dockerfile is written for the base image alpine:3.5. The resulting image has 26 packages installed by distribution tools (apk), 10 packages installed by pip3 (docker-py, tornado, pytz and dependencies), image size is 72 MB. In contrast, the jupyter/tmpnb image size is 596 MB, it has 351 (apt installed) packages and 11 packages installed by pip. I am testing alpine based image on tmpnb server in our university, seems to be OK.  I am not sure about version restrictions for pip installed packages, I used actual (newest) from pypi. 

Maybe, the mainstream tmpnb image can use Alpine base image, with not too much effort?

**Comment by willingc** [comment] 2017-04-17 14:14
Hi @misolietavec, 

Closing this as a duplicate of https://github.com/jupyterhub/configurable-http-proxy/issues/102. 👍

**Closed by willingc** 2017-04-17 14:14 UTC

**Comment by rgbkrk** [comment] 2017-04-17 17:29
Feel free to make a PR with the alpine base image.
